<?php

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_VERSION' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_VERSION', '1.0.0' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_SCRIPT_VERSION' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_SCRIPT_VERSION', CONNECTIONS_TO_DIRECTORIST_MIGRATOR_VERSION );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_FILE' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_FILE', dirname( dirname( __FILE__ ) ) . '/wilcity-to-directorist-migrator.php' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_BASE' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_BASE', dirname( dirname( __FILE__ ) ) . '/' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_LANGUAGE_DIR' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_LANGUAGE_DIR', CONNECTIONS_TO_DIRECTORIST_MIGRATOR_BASE . 'languages' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_POST_TYPE' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_POST_TYPE', 'wilcity-to-directorist-migrator' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_TEMPLATE_PATH' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_TEMPLATE_PATH', CONNECTIONS_TO_DIRECTORIST_MIGRATOR_BASE . 'template/' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_VIEW_PATH' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_VIEW_PATH', CONNECTIONS_TO_DIRECTORIST_MIGRATOR_BASE . 'view/' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_URL' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_URL', plugin_dir_url( CONNECTIONS_TO_DIRECTORIST_MIGRATOR_FILE ) );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_ASSET_URL' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_ASSET_URL', CONNECTIONS_TO_DIRECTORIST_MIGRATOR_URL . 'assets/dist/' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_JS_PATH' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_JS_PATH',  CONNECTIONS_TO_DIRECTORIST_MIGRATOR_ASSET_URL . 'js/' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_CSS_PATH' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_CSS_PATH', CONNECTIONS_TO_DIRECTORIST_MIGRATOR_ASSET_URL . 'css/' );
}

if ( ! defined( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_LOAD_MIN_FILES' ) ) {
    define( 'CONNECTIONS_TO_DIRECTORIST_MIGRATOR_LOAD_MIN_FILES', ! SCRIPT_DEBUG );
}